# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
substitutions:
    _DESAFIO_GO_VERSION: 1.0.0

steps:

    - name: 'gcr.io/cloud-builders/go'
      env: ['PROJECT_ROOT=desafio-go']
      args: ['test', './...']

    # Build image based on the Dockerfile
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/desafio-go-k8s', './desafio-go']
    
    # Push the container image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      env: ['PROJECT_ROOT=desafio-go']
      args: ['push', 'gcr.io/$PROJECT_ID/desafio-go-k8s']

images: 
- 'gcr.io/$PROJECT_ID/desafio-go-k8s:latest'